# /* eslint-disable */
# Custom Netlify Headers
# https://www.netlify.com/docs/headers-and-basic-auth/

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"


[[redirects]]
  from = "/*"
  to = "/Bourbon"
  status = 200
